[ global ]
    output_path = "../Outputs/DESAnalysis"

[ CovarianceMatrix ]
    input = "../Outputs/DES/DES.jld2"

[[ Analysis ]]
    output = "Draw"
    [ Analysis.draw ]
        num = 100
        SURVEY_LIST_SAMEMAGSYS = ["CFA3", "OTHER", "CALAN_TOLOLO"] 
        SURVEY_LIST_SAMEFILTER = ["CFA1", "CFA2", "CFA3", "CALAN_TOLOLO"]
